/**
 * VibeGuard – Refactoring Roadmap Generator
 * Produces educational Markdown from scan findings
 */

/**
 * Generate a Markdown refactoring roadmap
 * @param {Array} findings - All findings from SAST + AI audit
 * @param {number} score
 * @param {string} language
 * @returns {string} Markdown string
 */
function generateRoadmap(findings, score, language) {
  if (!findings || findings.length === 0) {
    return `## ✅ No Issues Found

Congratulations! Your code passed all security checks with a score of **${score}/100**.

**Best Practices to Maintain:**
- Continue using parameterized queries for database access
- Keep dependencies up to date (\`npm audit\` / \`pip audit\`)
- Enable HTTPS everywhere in production
- Use environment variables for all secrets
- Add security headers (CSP, HSTS, X-Frame-Options)

Your code is production-ready from a security standpoint. Keep up the great work!`;
  }

  const grouped = {
    Critical: findings.filter(f => f.severity === 'Critical'),
    High: findings.filter(f => f.severity === 'High'),
    Medium: findings.filter(f => f.severity === 'Medium'),
    Low: findings.filter(f => f.severity === 'Low'),
    Info: findings.filter(f => f.severity === 'Info'),
  };

  const icons = { Critical: '🚨', High: '🔴', Medium: '🟡', Low: '🟢', Info: '🔵' };
  const priorityLabel = score < 40
    ? '**Priority: Immediate action required before deployment.**'
    : score < 70
    ? '**Priority: Address before next release.**'
    : '**Priority: Good to fix in the next sprint.**';

  let md = `## 🗺️ VibeGuard Refactoring Roadmap

*Quality Score: **${score}/100** — ${priorityLabel}*

*Language: ${language} | Issues Found: ${findings.length}*

---

`;

  for (const [severity, items] of Object.entries(grouped)) {
    if (!items.length) continue;

    md += `## ${icons[severity]} ${severity} Priority (${items.length} issue${items.length > 1 ? 's' : ''})\n\n`;

    items.forEach((f, i) => {
      md += `### ${i + 1}. ${f.name}\n`;
      md += `- **Line:** ${f.line}\n`;
      md += `- **OWASP Category:** ${f.owasp || 'N/A'}\n`;
      if (f.source) md += `- **Detected By:** ${f.source}\n`;
      md += `\n`;

      md += `**Why This Matters:**\n${f.description}\n\n`;

      if (f.snippet) {
        md += `**Vulnerable Code:**\n\`\`\`\n${f.snippet}\n\`\`\`\n\n`;
      }

      md += `**How to Fix:**\n\`\`\`\n${f.fix}\n\`\`\`\n\n`;
      md += `---\n\n`;
    });
  }

  md += `## 📋 General Hardening Checklist

After addressing the issues above, apply these general security measures:

- [ ] **Dependency Audit**: Run \`npm audit --fix\` or \`pip-audit\` to patch known vulns in dependencies
- [ ] **Environment Variables**: Move ALL secrets to \`.env\` files (never commit them)
- [ ] **HTTPS Enforcement**: Redirect all HTTP traffic to HTTPS in production
- [ ] **Security Headers**: Add CSP, HSTS, X-Content-Type-Options, X-Frame-Options
- [ ] **Input Validation**: Validate and sanitize all user inputs server-side
- [ ] **Error Handling**: Replace broad try/catch with specific handlers and structured logging
- [ ] **Rate Limiting**: Add rate limiting to all API endpoints to prevent abuse
- [ ] **Least Privilege**: Ensure database users/service accounts have minimum required permissions

*Generated by VibeGuard · ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}*
`;

  return md;
}

/**
 * Convert Markdown to safe HTML for display
 * @param {string} md
 * @returns {string} HTML string
 */
function markdownToHtml(md) {
  return md
    // Code blocks
    .replace(/```[\w]*\n([\s\S]*?)```/g, (_, code) =>
      `<pre><code>${escHtml(code.trim())}</code></pre>`)
    // Inline code
    .replace(/`([^`]+)`/g, (_, code) => `<code>${escHtml(code)}</code>`)
    // Bold
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')
    // H2
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    // H3
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    // Checkbox items
    .replace(/^- \[ \] (.+)$/gm, '<li style="list-style:none;margin-left:-1rem">☐ $1</li>')
    // Bullet list
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // Numbered list
    .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
    // HR
    .replace(/^---$/gm, '<hr style="border-color:rgba(255,255,255,0.08);margin:1rem 0">')
    // Paragraphs (double newlines)
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(?!<[hpluio]|<\/|<pre|<hr)(.+)$/gm, '<p>$1</p>')
    // Clean up empty p tags
    .replace(/<p>\s*<\/p>/g, '')
    .replace(/<p>(<h[23]>)/g, '$1')
    .replace(/(<\/h[23]>)<\/p>/g, '$1');
}

function escHtml(s) {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}
